### ISSUE TITLE
Commanding villagers to build a wonder aborts the game

### ISSUE THREAD

**Issue by Andrew-Kelley** [Andrew-Kelley/Age_of_kingdoms#11]
Here is the error I got:
Enter a command: build wonder 90 40
Traceback (most recent call last):
  File "/Users/andrew/PycharmProjects/age_of_kingdoms/main.py", line 67, in <module>
    insert_command(player, command)
  File "/Users/andrew/PycharmProjects/age_of_kingdoms/command_handling.py", line 48, in insert_command
    insert_build_building_command(player, command)
  File "/Users/andrew/PycharmProjects/age_of_kingdoms/command_handling.py", line 111, in insert_build_building_command
    building_number = len(player.buildings[building_class.kind])
KeyError: 'wonder'

**Comment by Andrew-Kelley** [comment]
I fixed this bug in the commit "Fix bug: allow a wonder to be built"
